version: '3'
services:

  web:
      build:
        context: ../khibiny
        dockerfile: Dockerfile
      expose:
        - "8000"
      ports:
        - "8000:8000"
      volumes:
        - .:/app

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

  # volumes:
  #   - .:/app/