# Generated by Django 4.2.3 on 2023-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_travelcard_detail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelcard',
            name='detail_url',
        ),
        migrations.AlterField(
            model_name='travelcard',
            name='season',
            field=models.CharField(max_length=100),
        ),
    ]
