# Generated by Django 4.2.3 on 2023-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_travelcard_detail_url_alter_travelcard_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcard',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelcard',
            name='season',
            field=models.CharField(choices=[('winter', 'Зима'), ('summer', 'Лето')], max_length=10),
        ),
    ]
